/*
If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G
With a bigger example:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
If you are only given one colour as the input, return that colour.

https://www.codewars.com/kata/5a25ac6ac5e284cfbe000111/train/javascript

*/

//My solution: did it on my own, passed all the tests, then got help refactoring it

function triangle(row) {
  let currentRow = row.split('');

  while (currentRow.length > 1) {
    currentRow = currentRow.map((element, index) => funcMatrix[element][currentRow[index+1]])
    currentRow.pop()
  }

  return currentRow[0]
}

const funcMatrix = {R: {R: 'R', B: 'G', G: 'B'},
                    B: {R: 'G', B: 'B', G: 'R'},
                    G: {R: 'B', B: 'R', G: 'G'},
                   };

//other Solutions

const triangle = row => {
  let reduced = row.length > 1 ? '' : row;
  for (let i = 0; i < row.length - 1; i += 1) {
    reduced += row[i] == row[i+1] ? row[i] : 'RGB'.replace(row[i], '').replace(row[i+1], '');
  }
  return reduced.length > 1 ? triangle(reduced) : reduced;
}

//or

function triangle(row) {
  return row.length == 1 ? row : triangle(processedRow(row))
}

function processedRow(row) {
  return row.split('').map((el, i) => i == row.length-1 ? null : sumLetters(row[i], row[i+1])).join('');
}

function sumLetters(a, b) {
  switch (a+b) {
    case 'BG':
    case 'GB':
    case 'RR': return 'R'; break;
    case 'BR':
    case 'RB':
    case 'GG': return 'G'; break;
    case 'RG':
    case 'GR':
    case 'BB': return 'B'; break;
  }
}

//or

function triangle(row) {
  while (row.length > 1) {
    let newRow = ''

    for (let i = 0; i < row.length - 1; i += 1) {
      const lColor = row[i]
      const rColor = row[i + 1]

      newRow += getLastColor(lColor, rColor)
    }

    row = newRow
  }

  return row
}

function getLastColor(firstColor, secondColor) {
  if (firstColor === secondColor) {
    return firstColor
  }

  return 'RGB'.replace(firstColor, '').replace(secondColor, '')
}
